scoring-mlops
├── docker
│   ├── airflow
│   │   ├── Dockerfile
│   │   └── docker-compose.yml
│   ├── kafka
│   │   ├── Dockerfile
│   │   └── docker-compose.yml
│   └── mlflow
│       ├── Dockerfile
│       └── docker-compose.yml
├── src
│   ├── pipelines
│   │   ├── scoring.py
│   │   └── fraud_detection.py
│   ├── models
│   │   └── model.py
│   └── utils
│       └── config.py
├── tests
│   └── test_model.py
├── .env
├── .gitignore
├── docker-compose.yml
├── requirements.txt
└── README.md